---
name: Trainer
include:
- path: scripts/xcodegen/settings.yml
  relativePaths: false
- path: scripts/xcodegen/targetTemplates.yml
  relativePaths: false
- path: libraries/core/DependencyInjector/project.yml
  relativePaths: false
- path: libraries/core/LocalStorage/project.yml
  relativePaths: false
- path: libraries/core/DesignSystem/project.yml
  relativePaths: false
- path: libraries/domain/Authentication/project.yml
  relativePaths: false
- path: libraries/core/Coordinator/project.yml
  relativePaths: false
