############
# Targets
############

targets:

  DesignSystem:
    
    # templates
    templates: 
      - DynamicFramework
    
    # templateAttributes
    templateAttributes: 
      frameworkPath: libraries/core/DesignSystem
    
    dependencies:
     - target: DependencyInjector
      
    # scheme
    scheme:
      gatherCoverageData: true
      coverageTargets:
        - DesignSystem
      testTargets:
        - name: DesignSystemTests
          parallelizable: true
          randomExecutionOrder: true

  DesignSystemTests:
    
    # templates
    templates: 
      - FrameworkTests
    
    # templateAttributes
    templateAttributes: 
      frameworkPath: libraries/core/DesignSystem

    # dependencies
    dependencies:
      - target: DesignSystem

    